# Generated by Django 5.2.7 on 2026-01-20 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_person', models.CharField(verbose_name='شخص درخواست دهنده')),
                ('type_of_operation', models.CharField(verbose_name='نوع')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید ورود به انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_good', to='goods.goods', verbose_name='کالا')),
                ('good_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_good_supplier', to='supplier.goodsupplier', verbose_name='کالاهای مشتری')),
                ('registering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('supplier_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_supplier', to='supplier.supplier', verbose_name='تامین کننده')),
            ],
        ),
    ]
