# Generated by Django 5.2.7 on 2026-01-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='اسم برند یا شرکت')),
                ('contact_person', models.CharField(max_length=100, verbose_name='اسم شخص مسيول یا نماینده')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100, verbose_name='ادرس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت(اختیاری)')),
                ('national_id', models.CharField(max_length=100, verbose_name='شناسه ملی یا کد اقتصادی (برای ثبت رسمی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت در سیستم')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال یا غیر فعال بود تامین کننده')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کننده ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoodSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_goods', to='goods.goods')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.supplier')),
            ],
            options={
                'verbose_name': 'کالاها',
                'verbose_name_plural': 'کالاها',
                'ordering': ('-created_at',),
            },
        ),
    ]
